import { describe, it, expect } from 'vitest'
import { payrollEligibleUserWhere, payrollEligibleUserWhereForRange, PAYROLL_ROLES } from '@/lib/payroll-employee-scope'
import { payrollPeriodRange } from '@/lib/payroll-period'

/**
 * Bug found 2026-10-02: an employee HR disabled mid-period
 * (isrwd.bml@gmail.com, month=10/year=2026) had her payroll row correctly
 * generated by POST /api/payroll/generate, but both read paths that list
 * employees for the payroll table — app/(dashboard)/payroll/page.tsx and
 * GET /api/payroll/report — independently hardcoded `status: 'ACTIVE'` only,
 * so her existing row could never be rendered by either page. This file is
 * the single source of truth for the ACTIVE-or-DISABLED-in-period condition,
 * shared by all 3 call sites (generate/route.ts + the two fixed here) so
 * they can't drift apart like that again.
 */
describe('payrollEligibleUserWhereForRange', () => {
  it('includes the 3 payroll roles and an OR of ACTIVE / DISABLED-in-range', () => {
    const start = new Date(2026, 8, 21)
    const end = new Date(2026, 9, 20, 23, 59, 59, 999)

    const where = payrollEligibleUserWhereForRange(start, end)

    expect(where).toEqual({
      role: { in: [...PAYROLL_ROLES] },
      OR: [
        { status: 'ACTIVE' },
        { status: 'DISABLED', updatedAt: { gte: start, lte: end } },
      ],
    })
  })

  it('uses exactly the start/end passed in — never recomputes its own range', () => {
    const start = new Date(1999, 0, 1)
    const end = new Date(1999, 0, 31)

    const where = payrollEligibleUserWhereForRange(start, end) as any

    expect(where.OR[1].updatedAt).toEqual({ gte: start, lte: end })
  })
})

describe('payrollEligibleUserWhere(month, year) — convenience wrapper', () => {
  it('matches payrollEligibleUserWhereForRange(payrollPeriodRange(month, year))', () => {
    const { start, end } = payrollPeriodRange(10, 2026)

    const where = payrollEligibleUserWhere(10, 2026)

    expect(where).toEqual(payrollEligibleUserWhereForRange(start, end))
  })

  it('the exact isrwd.bml@gmail.com regression case: a DISABLED user updated on 2026-10-02 falls inside month=10/year=2026 (21 Sep – 20 Oct)', () => {
    const where = payrollEligibleUserWhere(10, 2026) as any
    const disabledUpdatedAt = new Date('2026-10-02T01:59:46.462Z')
    const { gte, lte } = where.OR[1].updatedAt

    expect(disabledUpdatedAt >= gte && disabledUpdatedAt <= lte).toBe(true)
  })

  it('excludes a DISABLED user updated well before the period starts', () => {
    const where = payrollEligibleUserWhere(10, 2026) as any
    const tooEarly = new Date('2026-08-01T00:00:00.000Z')
    const { gte, lte } = where.OR[1].updatedAt

    expect(tooEarly >= gte && tooEarly <= lte).toBe(false)
  })
})
