/** Fields safe to return from user GET/PATCH APIs (no secrets). */
export const SAFE_USER_SELECT = {
  id: true,
  name: true,
  email: true,
  employeeId: true,
  role: true,
  status: true,
  employeeType: true,
  managerId: true,
  teamLeaderId: true,
  department: true,
  position: true,
  baseSalary: true,
  socialSecurity: true,
  isCoworker: true,
  startDate: true,
  phone: true,
  lineId: true,
  lineUserId: true,
  lineDisplayName: true,
  prefix: true,
  nickname: true,
  birthDate: true,
  address: true,
  addressIdCard: true,
  nationalId: true,
  profileImage: true,
  branchId: true,
  divisionId: true,
  departmentId: true,
  sectionId: true,
} as const

/** Redacted select for MANAGER (no nationalId / baseSalary / addressIdCard). */
export const MANAGER_USER_SELECT = {
  id: true,
  name: true,
  email: true,
  employeeId: true,
  role: true,
  status: true,
  employeeType: true,
  managerId: true,
  teamLeaderId: true,
  department: true,
  position: true,
  socialSecurity: true,
  isCoworker: true,
  startDate: true,
  phone: true,
  lineId: true,
  lineUserId: true,
  lineDisplayName: true,
  prefix: true,
  nickname: true,
  birthDate: true,
  address: true,
  profileImage: true,
  branchId: true,
  divisionId: true,
  departmentId: true,
  sectionId: true,
} as const
