import { describe, it, expect, vi, beforeEach } from 'vitest'

// ── Mocks ──────────────────────────────────────────────────────────────────────

vi.mock('@/lib/auth', () => ({ auth: vi.fn() }))

vi.mock('@/lib/prisma', () => ({
  prisma: {
    user: { findMany: vi.fn() },
    payroll: { findMany: vi.fn() },
  },
}))

vi.mock('@/lib/branch-scope', () => ({
  buildBranchScope: vi.fn().mockReturnValue({}),
  branchUserWhere: vi.fn((_scope: unknown, extra: unknown) => extra ?? {}),
  branchNestedUserWhere: vi.fn().mockReturnValue(undefined),
  parseBranchQueryParam: vi.fn().mockReturnValue(undefined),
}))

vi.mock('@/lib/page-access', () => ({
  canAccessPage: vi.fn().mockReturnValue(true),
}))

vi.mock('@/lib/access-control', () => ({
  canApprovePayroll: vi.fn().mockReturnValue(true),
  PAYROLL_DELETE_ROLES: ['SUPER_ADMIN', 'CEO'],
}))

vi.mock('@/lib/ensure-payroll-payslip-columns', () => ({
  ensurePayrollPayslipColumns: vi.fn().mockResolvedValue(undefined),
}))

vi.mock('@/lib/cloudinary-service', () => ({
  isCloudinaryConfigured: vi.fn().mockReturnValue(true),
}))

// ── Imports (after mocks; lib/payroll-employee-scope + lib/payroll-period are
// deliberately left UN-mocked — this test exercises the real condition) ────────

import { auth } from '@/lib/auth'
import { prisma } from '@/lib/prisma'
import PayrollPage from '@/app/(dashboard)/payroll/page'

const hrSession = { user: { id: 'hr-1', name: 'HR', role: 'HR', branchId: null } }

/**
 * Bug found 2026-10-02: an employee disabled mid-period (the real case —
 * isrwd.bml@gmail.com, month=10/year=2026) had her payroll row correctly
 * generated by POST /api/payroll/generate, but this page's initial server-
 * rendered employee list independently hardcoded `status: 'ACTIVE'`, so her
 * row existed in the DB but could never be rendered here. Fixed by routing
 * through the shared lib/payroll-employee-scope.ts condition instead.
 *
 * PayrollPage is called directly as a plain async function (Next server
 * components are just functions) — the returned element tree is inspected
 * without a DOM render, since we only need to confirm what props.payrolls
 * PayrollClient receives, not anything about rendering.
 */
describe('PayrollPage — includes DISABLED-in-period employees (2026-10-02 bug fix)', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    vi.mocked(auth).mockResolvedValue(hrSession as any)
  })

  function findPayrollClientElement(root: any): any {
    const children = root.props.children
    const list = Array.isArray(children) ? children : [children]
    return list.find((c) => c && typeof c === 'object' && 'props' in c && 'payrolls' in c.props)
  }

  it('queries user.findMany with the same ACTIVE-or-DISABLED-in-period OR condition generate/route.ts uses', async () => {
    vi.mocked(prisma.user.findMany).mockResolvedValue([] as any)
    vi.mocked(prisma.payroll.findMany).mockResolvedValue([] as any)

    const now = new Date()
    const month = now.getMonth() + 1
    const year = now.getFullYear()

    await PayrollPage({ searchParams: Promise.resolve({}) })

    const call = vi.mocked(prisma.user.findMany).mock.calls[0][0] as any
    expect(call.where.role).toEqual({ in: ['EMPLOYEE', 'MANAGER_HR', 'LAWYER'] })
    expect(call.where.OR[0]).toEqual({ status: 'ACTIVE' })
    expect(call.where.OR[1].status).toBe('DISABLED')
    expect(call.where.OR[1].updatedAt.gte).toBeInstanceOf(Date)
    expect(call.where.OR[1].updatedAt.lte).toBeInstanceOf(Date)
    // Sanity: the range this month/year actually produces still contains "now".
    expect(now >= call.where.OR[1].updatedAt.gte && now <= call.where.OR[1].updatedAt.lte).toBe(true)
    void month
    void year
  })

  it("includes a DISABLED-in-period employee's existing payroll row in PayrollClient's props — the exact isrwd.bml@gmail.com regression", async () => {
    vi.mocked(prisma.user.findMany).mockResolvedValue([
      {
        id: 'emp-disabled', name: 'นางสาวอิสราวดี บุญมาเลิศ', employeeId: 'E9',
        department: 'ฝ่ายบัญชี', position: 'พนักงาน', socialSecurity: true,
        baseSalary: 30000, lineUserId: null,
      },
    ] as any)
    const now = new Date()
    const month = now.getMonth() + 1
    const year = now.getFullYear()
    vi.mocked(prisma.payroll.findMany).mockResolvedValue([
      {
        id: 'pr-disabled', userId: 'emp-disabled', month, year,
        baseSalary: 30000, lateDeduction: 0, absentDeduction: 0, unpaidLeave: 0,
        socialSecurity: 0, netSalary: 27309.01, lateDays: 0, absentDays: 0,
        lateMinutes: 0, lateBillableMinutes: 0, lateDeductionDetail: null,
        status: 'DRAFT',
        note: '⚠️ บัญชีถูกปิดใช้งานในเดือนนี้ — กรุณาตรวจสอบก่อนอนุมัติ',
        payslipSentAt: null, payslipSentVia: null, payslipSentStatus: null, payslipSentError: null,
        user: { name: 'นางสาวอิสราวดี บุญมาเลิศ', employeeId: 'E9', department: 'ฝ่ายบัญชี', position: 'พนักงาน', socialSecurity: true },
      },
    ] as any)

    const result = await PayrollPage({ searchParams: Promise.resolve({}) })
    const payrollClientEl = findPayrollClientElement(result as any)

    expect(payrollClientEl).toBeTruthy()
    const payrolls = payrollClientEl.props.payrolls
    expect(payrolls).toHaveLength(1)
    expect(payrolls[0].name).toBe('นางสาวอิสราวดี บุญมาเลิศ')
    expect(payrolls[0].hasPayroll).toBe(true)
    expect(payrolls[0].netSalary).toBe(27309.01)
  })

  it('still excludes a DISABLED employee updated well before this payroll period (not everyone-DISABLED — only in-period)', async () => {
    vi.mocked(prisma.user.findMany).mockResolvedValue([] as any)
    vi.mocked(prisma.payroll.findMany).mockResolvedValue([] as any)

    await PayrollPage({ searchParams: Promise.resolve({}) })

    const call = vi.mocked(prisma.user.findMany).mock.calls[0][0] as any
    const longAgoDisabled = new Date(0)
    const { gte, lte } = call.where.OR[1].updatedAt
    expect(longAgoDisabled >= gte && longAgoDisabled <= lte).toBe(false)
  })
})
